pool:
  name: Azure Pipelines

steps:
- bash: |
   # Write your commands here
   pat=$(github-pat)
   ls -la
   git remote add --mirror=fetch adobeRepo https://brianasz:$pat@github.com/brianasz/gs-spring-boot.git
   git fetch origin
   git push adobeRepo --all

  displayName: 'Sync Repos'



