name: Synchronization Process

trigger:
  branches:
    include:
      - develop

jobs:
- job: Sync_Job
  displayName: 'Synchronizing repositories'
  workspace:
    clean: all
  steps:
  - bash: |
      set -x
      ls -l
      git config --global user.email "brianasz@protonmail.com"
      git config --global user.name "Briana Sanchez"
      git remote set-url origin https://$(System.AccessToken)@dev.azure.com/brianasz/Java-SpringBoot-Maven/_git/Java-SpringBoot-Maven
      git remote add --mirror=fetch adobeRepository https://brianasz:$PAT@github.com/brianasz/ado-testing.git
      git remote -v
      git checkout $BRANCH
      git pull origin master
      git push adobeRepository --all
    displayName: 'Sync Repostories'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      PAT: $(githubPat)
      BRANCH: $(Build.SourceBranchName)