name: Synchronization Process

trigger: none

jobs:
- job: Sync_Job
  displayName: 'Synchronizing repositories'
  workspace:
    clean: all
  steps:
  - bash: |
      git remote set-url origin https://$(System.AccessToken)@dev.azure.com/brianasz/Java-SpringBoot-Maven/_git/Java-SpringBoot-Maven
      git remote add --mirror=fetch adobeRepository https://brianasz:$PAT@github.com/brianasz/ado-testing.git
      git fetch
      git checkout $BRANCH
      git push adobeRepository develop
    displayName: 'Sync Repostories'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      PAT: $(githubPat)
      BRANCH: $(Build.SourceBranchName)