name: Synchronization Process

trigger:
  branches:
    include:
      - master

resources:
    repositories:
    - repository: adobeRepo
      type: github
      name: brianasz/ado-testing
      endpoint: brianasz
jobs:
- job: Sync_Job
  displayName: 'Synchronizing repositories'
  workspace:
    clean: all
  steps:
  - checkout: self
  - bash: |
      ls -l
      git config --global user.email "brianasz@protonmail.com"
      git config --global user.name "Briana Sanchez"
      git remote set-url origin https://$(System.AccessToken)@dev.azure.com/brianasz/Java-SpringBoot-Maven/_git/Java-SpringBoot-Maven
      git remote add --mirror=fetch adobeRepository https://brianasz:$PAT@github.com/brianasz/ado-testing.git
      git pull origin master
      git push adobeRepository --all
    displayName: 'Sync Repostories'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      PAT: $(githubPat)
      BUILD: $(Build.BuildId)
#    - bash: |
    # Write your commands here
#    set -x
#    TIMESTAMP=`date +%Y-%m-%d_%H-%M-%S`
#    ls -la
#    git config --global user.email "brianasz@protonmail.com"
#    git config --global user.name "Briana Sanchez"
#    git remote add --mirror=fetch adobeRepo https://brianasz:$PAT@github.com/brianasz/ado-testing.git
#    git checkout -b $BUILD
#    git add *
#    git commit -m "$TIMESTAMP - Syncronization Process"
#    git push adobeRepo --all
#    env:
#        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
#        PAT: $(githubPat)
#        BUILD: $(Build.BuildId)
#    displayName: 'Sync Repos'