#variables:
#  system_accesstoken: $(System.AccessToken)
  
steps:
- bash: |
   # Write your commands here
   ls -la
   git remote add --mirror=fetch adobeRepo https://brianasz:$PAT@github.com/brianasz/gs-spring-boot.git
   git push adobeRepo --all
  env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      PAT: $(githubPat)
  displayName: 'Sync Repos'